services:
  catalogue:
      build:
        dockerfile: catalogue.Dockerfile
      image: ak3852/catalogue:1.0.0
      containaer_name: catalogue
      depends_on:
      - mongodb
  mongodb:
      build: 
        dockerfile: mongodb.Dockerfile # it moves to mongodb directory
      image: ak3852/mongodb:1.0.0 # docker build -t ak3852/mongodb:1.0.0
      containaer_name: mongodb


networks:
  default:
   driver: bridge
   name: roboshop
   external: false # if true, you need to create network manually      